server:
  port: ${PORT:8080}
  origin: ${ORIGIN:*}
spring:
  application:
    name: cargame
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://admin:admin@cluster0.ynuiaxk.mongodb.net/cargame?retryWrites=true&w=majority}

  rabbitmq:
    addresses: ${BUS_URI:amqps://kvdnonbt:xxqBEVOcaNckkM_ophoCco2y1yFc-WDF@woodpecker.rmq.cloudamqp.com/kvdnonbt}
