server:
  port: 8080
  origin: ${ORIGIN:*}
spring:
  application:
    name: cargame
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://desierra:admin@cluster0.f49rfgl.mongodb.net/cargame?retryWrites=true&w=majority}

  rabbitmq:
    addresses: ${BUS_URI:amqps://plqjfazy:u1ESotT1SCKsjEAQ5XwwRVL4bN99GUYk@moose.rmq.cloudamqp.com/plqjfazy}
